try {
	var a = 1;
	var b = a(2);
} catch (Exception e) {
	print e.message;
}